### ISSUE TITLE
[São Paulo/SP] Engenheiro DevOps na Viva Decora

### ISSUE THREAD

**Issue by mlinsgomes** [DevOps-Brazil/Vagas#130]
### Sobre a vaga

Você acredita que um trabalho é bom se o time é bom? Não tem medo de fazer parte de um time pequeno que já conseguiu grandes resultados? Acredita que a tecnologia é um meio para um fim e adora dormir tranquilo sabendo que seu trabalho foi bem feito? Além disso, você tem conhecimentos em AWS, IaC, CI/CD, Docker e Python?

### Quem somos

A Viva Decora foi fundada em 2014 e partiu da necessidade de completar o ciclo do consumidor de móveis online. Iniciamos as atividades com o apoio da estrutura de back-office do VivaReal e depois ganhamos equipes independentes de marketing B2B e B2C, operações, produto e engenharia, atualmente com mais de 20 profissionais.

Nossa plataforma de arquitetura e decoração online é voltada para ajudar os usuários a criar e comprar móveis e objetos para ambientes, baseado em recomendações e inspirações de diferentes arquitetos e designers. Temos mais de 8 milhões de sessões mensais! Tudo isso com um time de tecnologia focado e enxuto. Em 2020 passamos a fazer parte do grupo Duratex.

### O que buscamos

Uma pessoa desenvolvedora devops com nível pleno ou sênior. Procuramos alguém que entregue valor para o negócio executando tarefas como:

- Criação e Manutenção dos componentes da nossa infra-estrutura;
- Especificação e desenvolvimento de API's;
- Refactoring de componentes para se adequarem à mudanças nas regras de negócios;
- Análise crítica da qualidade do código dos pares;

### Conhecimentos necessários

- Ler o código dos seus pares antes de escrever o seu
- Trabalhar na mesma base de código que seus companheiros sem medo de conflito
- Avaliar o impacto das suas decisões de arquitetura e design
- Conversar com o time de design, backend e produto compartilhando dos mesmos objetivos
- 2 anos de experiência em IaC, CI/CD e ambiente de nuvem com preferência por ansible, cloudformation, Jenkins e AWS (Elastic Beanstalk, Cloudfront, S3, RDS e Route 53).
- 1 ano de experiência com desenvolvimento de software, com preferência por Python

### Conhecimentos desejáveis (não são eliminatórios)

- Django, celery
- javascript
- single page applications
- kubernetes
- Terraform

### Dia a dia

Como DevOps você aqui vai trabalhar para manter a entrega contínua da nossa aplicação, colaborar com a difusão da cultura DevOps dentro do time, e manter a infraestrutura necessária para as aplicações (IaC) trabalhando com tecnologias como ansible, cloudformation, Docker e Python.
As ferramentas que usamos no dia a dia incluem GitHub, New Relic, ELK, Jira, Slack, Kanban, Google Meets e nossa versão adaptada do Scrum.
O time de engenharia conta com 8 desenvolvedores, 3 designers, 1 gerente de produtos e 1 analista SEO. É muito comum conversarmos diariamente sobre as demandas para alinhar expectativas e compartilhar ideias.

### Nós oferecemos

Um time de engenharia pequeno, focado e que costuma trabalhar em pares
Um fluxo de trabalho bem definido do início ao fim das tarefas
Uma crença na autonomia dos nossos desenvolvedores e no alinhamento do time

### Local

Atualmente remoto, mas ao retorno presencialmente, nosso escritório fica em São Paulo - SP na Av. Paulista.

### Benefícios

Plano de saúde/odontológico
VR de R$ 30/dia
Auxílio creche

### Modalidade de contratação

CLT

### Candidate-se

 - Através do [LinkedIn](https://www.linkedin.com/jobs/view/2574540642/), ou
 - Envie um email para: marco.gomes@vivadecora.com.br com o seu currículo em anexo e o seguinte título: `[Vaga DevOps] Nome completo`

**Comment by teles** [comment]
Grandes lendas como @iuryalves e @DineshTrivedi já trabalharam nessa posição! Recomendo bastante o time!
