### ISSUE TITLE
[remoto] devOPS | aiqfome

### ISSUE THREAD

**Issue by monicapio** [DevOps-Brazil/Vagas#208]
## Nossa empresa
aiqfome
Somos a primeira e a maior plataforma de delivery online para restaurantes 100% brasileira, levando tecnologia e a melhor experiência em entrega pra todo o interior do Brasil!

Somos parte do Grupo Magazine Luiza, compartilhando o sonho de digitalizar todo o Brasil e trazer tecnologia pra todo mundo!

A gente se reinventa a todo momento e estamos revolucionando o mercado local de delivery, sem abrir mão de um valor inegociável: tratamos os outros como gostaríamos de ser tratados, criando soluções únicas e proporcionando a melhor experiência possível sempre, pra todo mundo envolvido!

Ah, e o mais importante: nos divertimos MUITO enquanto fazemos tudo isso!

Por isso, atenção: só contratamos pessoas legais 😉💜

## Descrição da vaga
Sua missão é “manter a estrutura de pé” e cuidar de todo o ciclo de vida da aplicação. Ter sempre em mente a responsabilidade de ajudar pessoas, otimizar processos e trazer o desenho das melhores soluções para cuidar com muito carinho dos nossos produtos.

**Coisas que você precisa fazer pra mandar muito bem aqui:**

- Ser o(a) guardiã(o) da nossa estrutura, arquiteto(a) das soluções e referência para o nosso time produtech em todos os sentidos, demonstrando sua paixão por tecnologia e integração de times, estimulando a inovação de forma contínua! 
- Monitorar a performance de aplicações;
- Automação de processos envolvendo o lifecyle das aplicações;
- Buscar ser uma referência técnica na disciplina envolvendo toda nossa infraestrutura;
- Melhorar e garantir a visibilidade da infra;
- Projetar, documentar e dar manutenção em ambientes;
- Entender os usos e alocar recursos corretamente.

**Requisitos**
**Antes de qualquer coisa, você precisa ser MUITO gente boa e teamplayer!**
**Mas também é importante que tenha:**

- boa comunicação
- amar a integração desenvolvimento + operações = 💜

**Seria massa se tiver entendimento de:** 

- Escalabilidade de sistemas;
- Rightsizing de recursos;
- Conhecimentos em segurança da Informação;
- Conhecimento em metodologias ágeis; 
- Sistema Operacional Linux;
- Arquitetura de microsserviços em nuvem AWS, ECS, RDS, ERC, EC2, ELBs;
- Ferramentas como Git, CloudWatch, Docker, Kubernetes, Bitbucket pipelines, Cloud Formation, RDS Insights;
- Ciclo de desenvolvimento de software automatizado (coding, building, integrations, tests, QA, Staging, deployment).

**Contratação**
CLT

**Benefícios**

- Opção de trampo full remoto
- Bônus por metas atingidas
- Cupons mensais pra pedir no aiq
- Descontos em cursos
- App de saúde mental (terapia online)
- Plano odontológico
- Plano de saúde
- Vale alimentação
- Vale transporte
- Seguro de vida
- Dois monitores pra trabalho
- Cafézin expresso e moído na hora
- Uma cultura de autonomia e diversidade
- Não temos nenhum dress code
- E a chance de você crescer aqui dentro é imensa!

**Nível**
Júnior

**Como se candidatar**
Se inscreva na vaga [aqui](https://aiqfome.gupy.io/jobs/1326238)

**Comment by irvinglucas** [comment]
Olá, boa noite! Ainda estão recebendo inscrições?
