### ISSUE TITLE
[Faria Lima/SP] Pessoa Analista SRE DEVOPS SR | DQR Tech

### ISSUE THREAD

**Issue by CarolCerqueira** [DevOps-Brazil/Vagas#411]
**Sobre a DQR TECH | Qualidade do começo ao fim**

A DQR TECH é uma consultoria parceira dos seus clientes, que possui um ecossistema de serviços, atuando de forma abrangente em todo ciclo de desenvolvimento de software. Desde a concepção e desenvolvimento até a manutenção e sustentação.
Levando soluções aos seus desafios de tecnologia, na forma de Projetos, Outsoucing e Squad.

**O QUE NOS MOVE:**

Pessoas & Tecnologia! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente do setor financeiro.

**DE ONDE VOCÊ VAI TRABALHAR?**

De 2X a 3X por semana híbrido na Faria Lima em São Paulo.

**O QUE ESPERAMOS QUE VOCÊ SAIBA:**

- Formação superior completa em engenharia, ciências da computação ou áreas relacionadas.
- Conhecimento em AWS: Cognito, AURORA PostgreSQL, EKS, Lambda, S3, API Gateway, DynamoDB, EC2, DocumentDB, SNS e OpenSearch.
- Mensageria/Streaming: RabbitMQ, SQS, Kafka e Kinesis
- Conhecimentos de infra as code: CloudFormation e Terraform.
- Conhecimento de K8s: rightsizing de recursos, provisionamento de novos serviços, otimização de serviços existentes e arquitetura k8s.
- Conhecimento em Windows Server (AD, IIS, Windows Services).
- Conhecimento em CI/CD: Jenkins e Azure DevOps.
- Conhecimento em scripting/programação: Shell e Python.
- Boa capacidade de comunicação para promover a cultura DevOps.

**O QUE SERIA LEGAL SE VOCÊ TIVESSE:**

- Cloud: GCP e Azure.
- CI/CD: Stack AWS e GitLab CI.
- Banco de dados: SQL, NoSQL e Postgres.
- Desenvolvimento: Kotlin, Java, Go e experiência com Spring Boot.
- Observabilidade: Datadog, Grafana, Prometheus, Zabbix, New Relic e Dynatrace.
- Bigdata: Stack AWS

**O QUE OFERECEMOS PARA VOCÊ?**

- Auxílio flexível para gastar como quiser (vale alimentação );
- Assistência médica e odontológica gratuita para você (sem coparticipação ou mensalidade),
- Você ainda pode incluir seus dependentes legais com apenas 50% de desconto da mensalidade em folha;
- Oferecemos auxílio Psicológico através da Psicologia Viva, estendida para dependentes;
- Auxílio creche (segundo as condições vigentes da convenção coletiva do Sindpd-SP);
- Seguro de vida em grupo;
- Aqui a sua indicação vale premiação de R$ 1.000,00;
- No mês do seu aniversário tem mimos;
- Auxílio Educação da Alura;
- Notebook para o desempenho das atividades;
- Contrato CLT.

**Todas nossas vagas são destinadas a Pluralidade e Diversidade**

ENVIE SEU MATERIAL PARA: vagas@dqrtech.com.br

![MicrosoftTeams-image (2)](https://github.com/DevOps-Brazil/Vagas/assets/154989598/4fb9fa5a-afc8-422c-a20a-5136a4c2e90e)

**Comment by DaianeMFirmiano** [comment]
VEM pra DQR TECH!!!
